///|
pub extend Decoder with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FetchBody with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FetchBody with Eq::{not_equal, equal}

///|
pub extend FetchInfo with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FetchInfo with Eq::{not_equal, equal}

///|
pub extend ImapError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ImapValue with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ImapValue with Eq::{not_equal, equal}

///|
pub extend MailboxAccess with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MailboxAccess with Eq::{not_equal, equal}

///|
pub extend Response with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Response with Eq::{not_equal, equal}

///|
pub extend SelectionInfo with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SelectionInfo with Eq::{not_equal, equal}

///|
pub extend Session with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend State with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend State with Eq::{not_equal, equal}

///|
pub extend TypedResponse with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TypedResponse with Eq::{not_equal, equal}

///|
pub extend UidIdentity with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UidIdentity with Eq::{not_equal, equal}

///|
pub extend UidRange with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UidRange with Eq::{not_equal, equal}

///|
pub extend UidSet with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UidSet with Eq::{not_equal, equal}
